# Generated by Django 3.2.20 on 2023-08-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230810_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('developer', 'Developer'), ('data_scientist', 'Data Scientist'), ('dba', 'Database Admin')], default='student', max_length=25),
        ),
    ]
